In [6]:
import numpy as np

In [11]:
arr = np.array([[1,2],[3,4],[5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
#square root
np.sqrt(arr)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [16]:
#exponent
np.exp(arr)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003],
       [148.4131591 , 403.42879349]])

In [20]:
A = np.random.randn(10)

A

array([ 0.3106976 , -0.0064216 , -0.32490841,  0.37536242, -0.66869948,
       -0.17746513,  0.95376698, -0.95781032,  0.49206954, -0.73149748])

In [23]:
B = np.random.randn(10)

B

array([ 1.11816665,  0.3117843 , -1.09621763,  0.20912942,  1.92831581,
        0.61414678,  1.20320522, -2.14706914,  0.19046009,  0.32209739])

In [26]:
# Binary Functions

In [29]:
#Add arrays
np.add(A,B)

array([ 1.42886426,  0.3053627 , -1.42112605,  0.58449184,  1.25961633,
        0.43668165,  2.1569722 , -3.10487946,  0.68252963, -0.4094001 ])

In [32]:
#find maximum 
np.maximum(A,B)

array([ 1.11816665,  0.3117843 , -0.32490841,  0.37536242,  1.92831581,
        0.61414678,  1.20320522, -0.95781032,  0.49206954,  0.32209739])

In [35]:
#find maximum
np.minimum(A,B)

array([ 0.3106976 , -0.0064216 , -1.09621763,  0.20912942, -0.66869948,
       -0.17746513,  0.95376698, -2.14706914,  0.19046009, -0.73149748])

In [38]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True